Fix bug that leads to `AttributeError: '_BTBuffer' object has no attribute '_nodes'`
- This fix may prevent Ferretti corrections from working. Needs to be tested